# Generated by Django 3.1 on 2020-08-25 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categrory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('photo', models.ImageField(upload_to='products')),
                ('pcat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.categrory')),
            ],
            options={
                'db_table': 'products',
            },
        ),
    ]
